name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: pack
      run: dotnet pack --no-build -o ./ 
    - name: publish nuget
      run: dotnet nuget push -s http://144.34.183.231:5555/api/v2/package/ -k oy2kqofnlm7gp2m2qtqqymkwv3uuedeuviwxjadqfrhefe *.nupkg 
    - name: publish symbols 
      run: dotnet nuget push -s http://144.34.183.231:5555/api/v2/package/ -k oy2kqofnlm7gp2m2qtqqymkwv3uuedeuviwxjadqfrhefe *.snupkg  